---
- name: install
  hosts: all

  tasks:
    - name: install => homebrew packages
      homebrew:
        state: present
        name:
          - ag
          - bash
          - bash-completion # TODO: configure
          - chruby
          - docker-compose
          - docker-machine
          - git
          - go
          - goenv
          - jq
          - kubernetes-cli
          - nmap
          - nvm # TODO: configure
          - python
          - ruby-install
          - sshuttle
          - terraform # TODO: configure
          - tig
          - tmux
          - vim
          - wget

    - name: install => homebrew cask packages
      homebrew_cask:
        state: present
        name:
          - appcleaner
          - chromedriver
          - docker
          - fly
          - flycut
          - google-cloud-sdk
          - graphiql
          - iterm2
          - lastpass
          - mas
          - multipass
          - sequel-pro
          - shiftit
          - slack
          - tunnelblick
          - vagrant
          - visual-studio-code
